sudo: false
language: python
install:
- pip install -r requirements_dev.txt

matrix:
  include:
  - python: 2.7
    env:
    - TOX_ENV=py27
  - python: 2.7
    env:
    - TOX_ENV=py27-flake8
  - python: 2.7
    env:
    - TOX_ENV=docs
  - python: 3.6
    env:
    - TOX_ENV=py36
  - python: 3.6
    env:
    - TOX_ENV=py36-flake8
  - python: 3.6
    env:
    - TOX_ENV=py36-black
  - python: 3.7
    env:
    - TOX_ENV=py37
  - python: 3.8
    env:
    - TOX_ENV=py38

script: tox -e $TOX_ENV
